[pytest]
testpaths =
    tests

python_files = test_*.py *_test.py
python_classes = Test* *Test
python_functions = test_*

# 控制台输出 + Allure 结果目录
# -v: 显示详细用例名
# -s: 显示 print/logging 输出
# --alluredir: Allure 结果输出目录
addopts = -vs --alluredir=reports/allure_results

markers =
    web: Web UI 用例
    android: Android App 用例
    ios: iOS App 用例
    smoke: 冒烟用例
    regression: 回归用例
